name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: date
      - run: ls .git
      - run: |
             trois_oeuvres_de moliere=(
             "Le Tartuffe ou l'Imposteur"
             "L'avare"
             "Le Bourgeois gentilhomme"
             )
     
      - run: npm install -g bats
      - run: bats -v
