name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: date
      - run: ls .git
      - run: IFS=':'
      - run: files="abc:abcdef"
      - run: ls ${files}
      - run: npm install -g bats
      - run: bats -v
